# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,RuleEngine}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\RuleEngine\Messenger\RuleEngineHandler:
        tags: [messenger.message_handler]


    App\RuleEngine\Actions\CreateVoucher\CreateVoucherActionType:
        tags:
            - { name: 'action_type', code: 'create_voucher' }
    App\RuleEngine\ConditionTypeFactory:
        calls:
            - method: registerConditionType
              arguments: ['data_comparison', App\RuleEngine\Conditions\DataComparison\DataComparisonConditionType]
    App\RuleEngine\ActionTypeFactory: ~
    App\RuleEngine\EventTypeFactory:
        calls:
            - method: registerEvent
              arguments: ['order_submitted', App\RuleEngine\Events\OrderSubmitted\OrderSubmittedEventType]
            - method: registerEvent
              arguments: ['asd', App\RuleEngine\Events\AsdEventType]

    App\RuleEngine\ContextDefinitionBuilder: ~

    App\RuleEngine\Validator\Constraint\ContextDefinitionValidator: ~
